// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJVZWRdQAVSP1Pgjc29xaKlH6koEhuJW8',
    appId: '1:710551656152:web:b9798d14ac9fb1883fe9ad',
    messagingSenderId: '710551656152',
    projectId: 'testhomeservice-8a305',
    authDomain: 'testhomeservice-8a305.firebaseapp.com',
    storageBucket: 'testhomeservice-8a305.appspot.com',
    measurementId: 'G-DP01JK1LPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BnUhrfFtLjgmyUjNzYHecdQmmVC1uRE',
    appId: '1:710551656152:android:a680326c58a371a53fe9ad',
    messagingSenderId: '710551656152',
    projectId: 'testhomeservice-8a305',
    storageBucket: 'testhomeservice-8a305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDymKe9v_sm-2fLwLyFtHWTjadwqeIen6U',
    appId: '1:710551656152:ios:b3b96a45b02580183fe9ad',
    messagingSenderId: '710551656152',
    projectId: 'testhomeservice-8a305',
    storageBucket: 'testhomeservice-8a305.appspot.com',
    iosClientId: '710551656152-43j983d6q8ob6ilm5dnjh8rm6e0jc5kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.day35',
  );
}
